### ISSUE TITLE
Why use SRV records?

### ISSUE THREAD

**Issue by tohojo** [ehloonion/onionmx#15]
What is the reason for using SRV records instead of simply having .onion MX records?

Also, none of the docs seem to mention dnssec as a way to verify the .onion addresses as being genuine?

**Comment by BlauerHunger** [comment]
probably to be still able to deliver clearnet emails without tor (to avoid untrustworthy exit relays) without any routing configuration

**Comment by tohojo** [comment]
Ah, didn't mean exclusively. But if there's just a higher priority MX record for a .onion you're basically saying "please send email via tor, and fallback to clearnet". Then all you need to so is teach mail servers how to resolve .onion domains, keeping compatibility with the existing DNS infrastructure for sending mail... :)

**Comment by immerda** [comment]
In general we saw MX records as a possible solution, but we were worrying how different MTAs are dealing with such records. Given that we need to anyway setup a dedicated route within MTAs configuration and they won't just transparently route email towards onion services (remember this is a solution where 99% of the traffic still flows over clearnet), we didn't really see anymore an advantage in an already occupied and very specific DNS type. SRV records are in our opinion a more generic and better approach to model such lookups.

We are working on a more formal document that describes our reasoning and also how we envision tranports to use SRV records.

I will close this ticket and like to ask any further disucssion to happen on the mailinglist: https://lists.immerda.ch/mailman/listinfo/onionmx
